[package]
name = "timelog"
version = "0.1.0"
authors = ["Andr√© Vicente Milack <andrevicente.m@gmail.com>"]
edition = "2018"
description = "Tool for registering work time"

[dependencies]
chrono = "0.4"
clap = "~2.32"
lazy_static = "1.2.0"
regex = "1"